import {
  IsString,
  IsNotEmpty,
  IsOptional,
  IsDateString,
  IsArray,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';

export class VerifyTicketDto {
  @IsString()
  @IsNotEmpty()
  ticketId: string;

  /**
   * The raw token extracted from the QR payload.
   * QR payload format v2: {ticketId}:{rawToken}:{gateId}
   */
  @IsString()
  @IsNotEmpty()
  token: string;

  @IsString()
  @IsNotEmpty()
  deviceId: string;

  /**
   * Gate ID assigned to this device (from PWA config).
   * Used to verify the QR belongs to this gate.
   */
  @IsString()
  @IsOptional()
  gateId?: string;
}

export class SyncCheckinRecordDto {
  @IsString()
  @IsNotEmpty()
  ticketId: string;

  @IsString()
  @IsNotEmpty()
  token: string;

  @IsString()
  @IsNotEmpty()
  deviceId: string;

  /**
   * Gate ID from the QR payload (parsed from QR code).
   */
  @IsString()
  @IsOptional()
  gateId?: string;

  @IsDateString()
  scannedAt: string;

  /**
   * Unique event ID generated by the mobile app for this scan.
   * Combined with deviceId to form the idempotency key: @@unique([deviceId, offlineEventId])
   */
  @IsString()
  @IsNotEmpty()
  offlineEventId: string;
}

export class SyncCheckinDto {
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => SyncCheckinRecordDto)
  records: SyncCheckinRecordDto[];
}

export class SyncCheckinResultDto {
  ticketId: string;
  offlineEventId: string;
  success: boolean;
  status: string;
  conflict: boolean;
  message: string;
}

export class SyncCheckinResponseDto {
  total: number;
  success: number;
  failed: number;
  conflicts: number;
  results: SyncCheckinResultDto[];
}

export class VerifyTicketResponseDto {
  success: boolean;
  ticketId: string;
  concertId: string;
  ticketTypeName: string;
  status: string;
  message: string;
}
